<a href="https://colab.research.google.com/github/Cyber-GenAI/machine-learning/blob/main/Classification/Technique_specificity_!!!.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# نصب کتابخانه‌های ضروری
#!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
#!pip install torch-geometric
#!pip install torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://data.pyg.org/whl/torch-2.0.0+cu118.html
#!pip install transformers
#!pip install networkx matplotlib seaborn pandas numpy scikit-learn
#!pip install MSTICPy
#!pip install optuna
#!pip install bayesian-optimization
#!pip install scikit-plot##
##!pip install plotly
#!pip install kaleido

# برای نمایش بهتر نمودارها در notebook
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# بررسی نسخه‌ها
# import torch
# print(f"PyTorch version: {torch.__version__}")
# print(f"CUDA available: {torch.cuda.is_available()}")
# if torch.cuda.is_available():
#     print(f"CUDA device: {torch.cuda.get_device_name(0)}")

In [ ]:
!curl -L https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json -o enterprise-attack.json

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 37.9M  100 37.9M    0     0  40.3M      0 --:--:-- --:--:-- --:--:-- 40.3M

In [ ]:
# Compress the data folder
#!zip -r ./data.zip ./data/

Next, we'll mount your Google Drive to save the compressed file.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
!cp /content/drive/MyDrive/data.zip /content/data.zip
!unzip /content/data.zip -d /content/
#!rm -rf /content/data.zip

Mounted at /content/drive
Archive:  /content/data.zip
   creating: /content/data/
  inflating: /content/data/technique_hierarchy.csv
  inflating: /content/data/threat_group_techniques_structured.json
  inflating: /content/data/tactic_techniques.csv
  inflating: /content/data/tactic_order.csv
  inflating: /content/data/group2idx.json
  inflating: /content/data/common_temporal_patterns.json
  inflating: /content/data/mordor_data_enriched.json
  inflating: /content/data/sequences_with_group_labels.csv
  inflating: /content/data/temporal_attack_graph.json
  inflating: /content/data/technique_hierarchy.json
  inflating: /content/data/combined_sequences.csv
  inflating: /content/data/sequence_data.json
  inflating: /content/data/idx2token.json
  inflating: /content/data/common_temporal_patterns.csv
  inflating: /content/data/tactic_order.json
  inflating: /content/data/idx2group.json
  inflating: /content/data/token2best_phase.json
  inflating: /content/data/token2tactic_rank.json
  inflating: /content/data/tactic_technique_details.json
  inflating: /content/data/tactic_techniques.json
  inflating: /content/data/temporal_sequences.json
  inflating: /content/data/techniques_without_subtechniques.json
  inflating: /content/data/token2phases.json
  inflating: /content/data/graph_adjacency_list.json
  inflating: /content/data/feature_vectors.csv
  inflating: /content/data/sequence_data_with_tactics.json
  inflating: /content/data/enterprise-attack.json
  inflating: /content/data/tactic_technique_details.csv
  inflating: /content/data/tactic_multilabels.csv
  inflating: /content/data/token2idx.json
  inflating: /content/data/mordor_data_enriched.csv

In [ ]:
import os
import pandas as pd

# List files in the data directory
data_dir = '/content/data/'
files = os.listdir(data_dir)
print("Files in the data directory:")
for file in files:
    print(file)

print("\n--- Inspecting CSV files ---")
# Inspect the first few rows of CSV files
for file in files:
    if file.endswith('.csv'):
        file_path = os.path.join(data_dir, file)
        try:
            print(f"\nHead of {file}:")
            df = pd.read_csv(file_path)
            display(df.head())
        except Exception as e:
            print(f"Could not read {file}: {e}")

Files in the data directory:
threat_group_techniques_structured.json
techniques_without_subtechniques.json
enterprise-attack.json
tactic_technique_details.csv
combined_sequences.csv
tactic_order.json
temporal_sequences.json
idx2group.json
sequence_data_with_tactics.json
mordor_data_enriched.csv
tactic_multilabels.csv
token2phases.json
technique_hierarchy.json
common_temporal_patterns.csv
token2tactic_rank.json
tactic_techniques.csv
group2idx.json
common_temporal_patterns.json
token2best_phase.json
mordor_data_enriched.json
graph_adjacency_list.json
feature_vectors.csv
tactic_techniques.json
temporal_attack_graph.json
technique_hierarchy.csv
tactic_order.csv
token2idx.json
idx2token.json
sequences_with_group_labels.csv
tactic_technique_details.json
sequence_data.json

--- Inspecting CSV files ---

Head of tactic_technique_details.csv:

,technique_id,technique_name,tactic,tactic_rank,description
0,T1055.011,Extra Window Memory Injection,defense-evasion,6,Adversaries may inject malicious code into pro...
1,T1055.011,Extra Window Memory Injection,privilege-escalation,5,Adversaries may inject malicious code into pro...
2,T1053.005,Scheduled Task,execution,3,Adversaries may abuse the Windows Task Schedul...
3,T1053.005,Scheduled Task,persistence,4,Adversaries may abuse the Windows Task Schedul...
4,T1053.005,Scheduled Task,privilege-escalation,5,Adversaries may abuse the Windows Task Schedul...

Head of combined_sequences.csv:

,intrusion_set_id,intrusion_set_name,sequence_tokens,sequence_indices,sequence_tactics,tactic_sequence,source,group_type
0,intrusion-set--c4d50cdf-87ce-407d-86d8-8628834...,APT-C-36,"['T1588.002', 'T1566.001', 'T1053.005', 'T1059...","[394, 341, 81, 96, 204, 41, 62, 151, 354]","['resource-development', 'initial-access', 'ex...","[1, 2, 3, 3, 3, 6, 6, 11, 11]",NaN,NaN
1,intrusion-set--6a2e693f-24e5-451a-9f88-b36a108...,APT1,"['T1583.001', 'T1584.001', 'T1585.002', 'T1588...","[367, 374, 383, 393, 394, 341, 342, 94, 63, 27...","['resource-development', 'resource-development...","[1, 1, 1, 1, 1, 2, 2, 3, 6, 6, 7, 8, 8, 8, 8, ...",NaN,NaN
2,intrusion-set--c47f937f-1022-4f42-8525-e7a4779...,APT12,"['T1566.001', 'T1203', 'T1204.002', 'T1102.002...","[341, 201, 204, 148, 350]","['initial-access', 'execution', 'execution', '...","[2, 3, 3, 11, 11]",NaN,NaN
3,intrusion-set--d6e88e18-81e8-4709-82d8-973095d...,APT16,['T1584.004'],[377],['resource-development'],[1],NaN,NaN
4,intrusion-set--090242d7-73fc-4738-af68-20162f7...,APT17,"['T1583.006', 'T1585']","[372, 381]","['resource-development', 'resource-development']","[1, 1]",NaN,NaN

Head of mordor_data_enriched.csv:

,TimeGenerated,technique_id,Computer,SubjectUserName,EventID,ProcessName,SourceIP,DestinationIP,LogonType,tactics,technique_name,technique_description,is_subtechnique,parent_technique,timestamp,step,rank
0,2025-01-01 08:00:00,T1087,WORKSTATION-1,user1,4624,lsass.exe,10.0.0.0,192.168.0.0,2,['discovery'],Account Discovery,Adversaries may attempt to get a listing of va...,False,NaN,2025-01-01 08:00:00,1,0.076923
1,2025-01-01 08:15:00,T1018,WORKSTATION-2,user2,4624,lsass.exe,10.0.1.1,192.168.1.1,2,['discovery'],Remote System Discovery,Adversaries may attempt to get a listing of ot...,False,NaN,2025-01-01 08:15:00,2,0.153846
2,2025-01-01 08:30:00,T1069,WORKSTATION-3,user3,4624,lsass.exe,10.0.2.2,192.168.2.2,2,['discovery'],Permission Groups Discovery,Adversaries may attempt to discover group and ...,False,NaN,2025-01-01 08:30:00,3,0.230769
3,2025-01-01 08:45:00,T1059.001,WORKSTATION-4,user1,4688,powershell.exe,10.0.3.3,192.168.0.3,2,['execution'],PowerShell,Adversaries may abuse PowerShell commands and ...,True,T1059,2025-01-01 08:45:00,4,0.307692
4,2025-01-01 09:00:00,T1047,WORKSTATION-5,user2,4624,lsass.exe,10.0.4.4,192.168.1.4,2,['execution'],Windows Management Instrumentation,Adversaries may abuse Windows Management Instr...,False,NaN,2025-01-01 09:00:00,5,0.384615

Head of tactic_multilabels.csv:

,intrusion_set_name,intrusion_set_id,ta_reconnaissance,ta_resource-development,ta_initial-access,ta_execution,ta_persistence,ta_privilege-escalation,ta_defense-evasion,ta_credential-access,ta_discovery,ta_lateral-movement,ta_collection,ta_command-and-control,ta_exfiltration,ta_impact
0,APT-C-36,intrusion-set--c4d50cdf-87ce-407d-86d8-8628834...,0,1,1,1,0,0,1,0,0,0,0,1,0,0
1,APT1,intrusion-set--6a2e693f-24e5-451a-9f88-b36a108...,0,1,1,1,0,0,1,1,1,1,1,0,0,0
2,APT12,intrusion-set--c47f937f-1022-4f42-8525-e7a4779...,0,0,1,1,0,0,0,0,0,0,0,1,0,0
3,APT16,intrusion-set--d6e88e18-81e8-4709-82d8-973095d...,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,APT17,intrusion-set--090242d7-73fc-4738-af68-20162f7...,0,1,0,0,0,0,0,0,0,0,0,0,0,0

Head of common_temporal_patterns.csv:

,pattern,length,frequency,pattern_sequence
0,defense-evasion → defense-evasion,2,495,"['defense-evasion', 'defense-evasion']"
1,execution → execution,2,437,"['execution', 'execution']"
2,discovery → discovery,2,429,"['discovery', 'discovery']"
3,defense-evasion → defense-evasion → defense-ev...,3,385,"['defense-evasion', 'defense-evasion', 'defens..."
4,discovery → discovery → discovery,3,339,"['discovery', 'discovery', 'discovery']"

Head of tactic_techniques.csv:

,tactic,tactic_rank,technique_id,technique_name
0,reconnaissance,0,T1589,Gather Victim Identity Information
1,reconnaissance,0,T1589.001,Credentials
2,reconnaissance,0,T1589.002,Email Addresses
3,reconnaissance,0,T1589.003,Employee Names
4,reconnaissance,0,T1590,Gather Victim Network Information

Head of feature_vectors.csv:

,index,intrusion_set_id,ta_reconnaissance,ta_resource-development,ta_initial-access,ta_execution,ta_persistence,ta_privilege-escalation,ta_defense-evasion,ta_credential-access,ta_discovery,ta_lateral-movement,ta_collection,ta_command-and-control,ta_exfiltration,ta_impact,sequence_length,num_unique_techniques
0,0,intrusion-set--c4d50cdf-87ce-407d-86d8-8628834...,0,1,1,1,0,0,1,0,0,0,0,1,0,0,9,9
1,1,intrusion-set--6a2e693f-24e5-451a-9f88-b36a108...,0,1,1,1,0,0,1,1,1,1,1,0,0,0,23,23
2,2,intrusion-set--c47f937f-1022-4f42-8525-e7a4779...,0,0,1,1,0,0,0,0,0,0,0,1,0,0,5,5
3,3,intrusion-set--d6e88e18-81e8-4709-82d8-973095d...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1
4,4,intrusion-set--090242d7-73fc-4738-af68-20162f7...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,2,2

Head of technique_hierarchy.csv:

,technique_id,technique_name,subtechnique_id,subtechnique_name
0,T1037,Boot or Logon Initialization Scripts,T1037.004,RC Scripts
1,T1037,Boot or Logon Initialization Scripts,T1037.001,Logon Script (Windows)
2,T1037,Boot or Logon Initialization Scripts,T1037.003,Network Logon Script
3,T1037,Boot or Logon Initialization Scripts,T1037.005,Startup Items
4,T1037,Boot or Logon Initialization Scripts,T1037.002,Login Hook

Head of tactic_order.csv:

                 tactic  rank
0        reconnaissance     0
1  resource-development     1
2        initial-access     2
3             execution     3
4           persistence     4

Head of sequences_with_group_labels.csv:

,intrusion_set_id,intrusion_set_name,sequence_tokens,sequence_indices,sequence_tactics,tactic_sequence,source,group_type,group_label_idx
0,intrusion-set--c4d50cdf-87ce-407d-86d8-8628834...,APT-C-36,"['T1588.002', 'T1566.001', 'T1053.005', 'T1059...","[394, 341, 81, 96, 204, 41, 62, 151, 354]","['resource-development', 'initial-access', 'ex...","[1, 2, 3, 3, 3, 6, 6, 11, 11]",NaN,NaN,0
1,intrusion-set--6a2e693f-24e5-451a-9f88-b36a108...,APT1,"['T1583.001', 'T1584.001', 'T1585.002', 'T1588...","[367, 374, 383, 393, 394, 341, 342, 94, 63, 27...","['resource-development', 'resource-development...","[1, 1, 1, 1, 1, 2, 2, 3, 6, 6, 7, 8, 8, 8, 8, ...",NaN,NaN,1
2,intrusion-set--c47f937f-1022-4f42-8525-e7a4779...,APT12,"['T1566.001', 'T1203', 'T1204.002', 'T1102.002...","[341, 201, 204, 148, 350]","['initial-access', 'execution', 'execution', '...","[2, 3, 3, 11, 11]",NaN,NaN,2
3,intrusion-set--d6e88e18-81e8-4709-82d8-973095d...,APT16,['T1584.004'],[377],['resource-development'],[1],NaN,NaN,3
4,intrusion-set--090242d7-73fc-4738-af68-20162f7...,APT17,"['T1583.006', 'T1585']","[372, 381]","['resource-development', 'resource-development']","[1, 1]",NaN,NaN,4

# Task
Create a Python script to process "sequences_with_group_labels.csv" and "technique_hierarchy.csv". The script should read "sequences_with_group_labels.csv" row by row, extract the `intrusion_set_id` and `sequence_tokens`. For each `sequence_tokens`, replace any sub-technique with its parent technique based on the mapping provided in "technique_hierarchy.csv". Finally, create a new CSV file containing the `intrusion_set_id`, `intrusion_set_name`, and the modified `sequence_tokens`. The script should be executable in Google Colab.

## Load the datasets

### Subtask:
Load `technique_hierarchy.csv` and `sequences_with_group_labels.csv` into pandas DataFrames.

**Reasoning**:
Load the specified CSV files into pandas DataFrames.

In [ ]:
technique_hierarchy_df = pd.read_csv('/content/data/technique_hierarchy.csv')
sequences_df = pd.read_csv('/content/data/sequences_with_group_labels.csv')

## Create a subtechnique-to-parent technique mapping

### Subtask:
Create a subtechnique-to-parent technique mapping.

**Reasoning**:
Create an empty dictionary and iterate through the `technique_hierarchy_df` to populate it with the subtechnique-to-parent technique mapping.

In [ ]:
subtechnique_to_parent_mapping = {}
for index, row in technique_hierarchy_df.iterrows():
    if pd.notnull(row['subtechnique_id']):
        subtechnique_to_parent_mapping[row['subtechnique_id']] = row['technique_id']

# Display a few entries to verify
print("Sample subtechnique to parent mapping:")
for i, (subtech, parent_tech) in enumerate(subtechnique_to_parent_mapping.items()):
    if i < 10:
        print(f"{subtech}: {parent_tech}")
    else:
        break

Sample subtechnique to parent mapping:
T1037.004: T1037
T1037.001: T1037
T1037.003: T1037
T1037.005: T1037
T1037.002: T1037
T1557.003: T1557
T1557.002: T1557
T1557.001: T1557
T1557.004: T1557
T1583.008: T1583

## Process sequences

### Subtask:
Process sequences

**Reasoning**:
Iterate through the sequences DataFrame, process each sequence to replace sub-techniques with parent techniques

In [ ]:
#Reasoning: Iterate through the sequences DataFrame, process each sequence to replace sub-techniques with parent technique
import ast

processed_sequences = []

for index, row in sequences_df.iterrows():
    intrusion_set_id = row['intrusion_set_id']
    intrusion_set_name = row['intrusion_set_name']
    # Safely evaluate the string representation of the list
    sequence_tokens = ast.literal_eval(row['sequence_tokens'])

    modified_tokens = []
    for token in sequence_tokens:
        if token in subtechnique_to_parent_mapping:
            modified_tokens.append(subtechnique_to_parent_mapping[token])
        else:
            modified_tokens.append(token)

    # Append the processed sequence as a list in a single column
    processed_sequences.append({
        'intrusion_set_id': intrusion_set_id,
        'intrusion_set_name': intrusion_set_name,
        'processed_sequence_tokens': modified_tokens  # Keep the tokens as a list
    })

# Display the first few processed sequences to verify
print("Sample processed sequences:")
for i, seq_data in enumerate(processed_sequences):
    if i < 5:
        print(seq_data)
    else:
        break

Sample processed sequences:
{'intrusion_set_id': 'intrusion-set--c4d50cdf-87ce-407d-86d8-862883485842', 'intrusion_set_name': 'APT-C-36', 'processed_sequence_tokens': ['T1588', 'T1566', 'T1053', 'T1059', 'T1204', 'T1027', 'T1036', 'T1105', 'T1571']}
{'intrusion_set_id': 'intrusion-set--6a2e693f-24e5-451a-9f88-b36a108e5662', 'intrusion_set_name': 'APT1', 'processed_sequence_tokens': ['T1583', 'T1584', 'T1585', 'T1588', 'T1588', 'T1566', 'T1566', 'T1059', 'T1036', 'T1550', 'T1003', 'T1007', 'T1016', 'T1049', 'T1057', 'T1087', 'T1135', 'T1021', 'T1005', 'T1114', 'T1114', 'T1119', 'T1560']}
{'intrusion_set_id': 'intrusion-set--c47f937f-1022-4f42-8525-e7a4779a14cb', 'intrusion_set_name': 'APT12', 'processed_sequence_tokens': ['T1566', 'T1203', 'T1204', 'T1102', 'T1568']}
{'intrusion_set_id': 'intrusion-set--d6e88e18-81e8-4709-82d8-973095da1e70', 'intrusion_set_name': 'APT16', 'processed_sequence_tokens': ['T1584']}
{'intrusion_set_id': 'intrusion-set--090242d7-73fc-4738-af68-20162f7a5aae', 'intrusion_set_name': 'APT17', 'processed_sequence_tokens': ['T1583', 'T1585']}

In [ ]:
processed_sequences_df = pd.DataFrame(processed_sequences)

# Display the first few rows of the new DataFrame
print("\nProcessed sequences DataFrame:")
display(processed_sequences_df.head())

Processed sequences DataFrame:

,intrusion_set_id,intrusion_set_name,processed_sequence_tokens
0,intrusion-set--c4d50cdf-87ce-407d-86d8-8628834...,APT-C-36,"[T1588, T1566, T1053, T1059, T1204, T1027, T10..."
1,intrusion-set--6a2e693f-24e5-451a-9f88-b36a108...,APT1,"[T1583, T1584, T1585, T1588, T1588, T1566, T15..."
2,intrusion-set--c47f937f-1022-4f42-8525-e7a4779...,APT12,"[T1566, T1203, T1204, T1102, T1568]"
3,intrusion-set--d6e88e18-81e8-4709-82d8-973095d...,APT16,[T1584]
4,intrusion-set--090242d7-73fc-4738-af68-20162f7...,APT17,"[T1583, T1585]"

In [ ]:
# Create a DataFrame from the processed sequences
processed_sequences_df = pd.DataFrame(processed_sequences)

# Define the output path for the Excel file
output_excel_path = '/content/processed_sequences_table.xlsx'

# Save the DataFrame to an Excel file
try:
    processed_sequences_df.to_excel(output_excel_path, index=False)
    print(f"Processed data saved to Excel file: {output_excel_path}")
except ImportError:
    print("Saving to Excel requires the 'openpyxl' library.")
    print("Please install it by running: !pip install openpyxl")
    # Fallback to CSV if openpyxl is not installed
    output_csv_path = '/content/processed_sequences_table.csv'
    processed_sequences_df.to_csv(output_csv_path, index=False, encoding='utf-8')
    print(f"Processed data saved to CSV file instead: {output_csv_path}")

Processed data saved to Excel file: /content/processed_sequences_table.xlsx

# Task
Analyze the techniques in the processed sequences data from "/content/processed_sequences_dataframe.csv" or "/content/processed_.csv" by calculating the total count and unique count for each technique across all sequences, and their corresponding specificity scores (1/count). Save the results in a new CSV file with columns: 'تکنیک', 'Non-Unique_total_count', 'Non-Unique_specificity_count_per_technique', 'Unique_total_count', and 'Unique_specificity_count_per_technique'.

## Load processed data

### Subtask:
Load the processed data from the saved CSV file (`/content/processed_sequences_dataframe.csv` or `/content/processed_.csv`) into a pandas DataFrame.

**Reasoning**:
Load the processed sequences data from the CSV file into a pandas DataFrame and prepare it for analysis.

**Reasoning**:
The specified CSV files were not found. The previous step saved the processed data to an Excel file. Load the data from the Excel file instead.

In [ ]:
import pandas as pd
import ast

# Define the path to the processed sequences data saved as Excel
excel_file_path = '/content/processed_sequences_table.xlsx'

# Load the Excel file into a pandas DataFrame
try:
    processed_sequences_df = pd.read_excel(excel_file_path)
except FileNotFoundError:
    print(f"Excel file not found at {excel_file_path}")
    # If the Excel file is not found, try to read the CSV fallback file again
    csv_file_path = '/content/processed_sequences_table.csv'
    try:
        processed_sequences_df = pd.read_csv(csv_file_path)
    except FileNotFoundError:
         raise FileNotFoundError("Processed sequences file not found at expected locations.")


# Convert the string representation of lists in 'processed_sequence_tokens' to actual lists
# This step is necessary because reading from Excel or CSV will store the list as a string
processed_sequences_df['processed_sequence_tokens'] = processed_sequences_df['processed_sequence_tokens'].apply(ast.literal_eval)

# Display the head and info of the loaded DataFrame
print("Head of the loaded processed sequences DataFrame:")
display(processed_sequences_df.head())

print("\nInfo of the loaded processed sequences DataFrame:")
processed_sequences_df.info()

Head of the loaded processed sequences DataFrame:

,intrusion_set_id,intrusion_set_name,processed_sequence_tokens
0,intrusion-set--c4d50cdf-87ce-407d-86d8-8628834...,APT-C-36,"[T1588, T1566, T1053, T1059, T1204, T1027, T10..."
1,intrusion-set--6a2e693f-24e5-451a-9f88-b36a108...,APT1,"[T1583, T1584, T1585, T1588, T1588, T1566, T15..."
2,intrusion-set--c47f937f-1022-4f42-8525-e7a4779...,APT12,"[T1566, T1203, T1204, T1102, T1568]"
3,intrusion-set--d6e88e18-81e8-4709-82d8-973095d...,APT16,[T1584]
4,intrusion-set--090242d7-73fc-4738-af68-20162f7...,APT17,"[T1583, T1585]"

Info of the loaded processed sequences DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   intrusion_set_id           167 non-null    object
 1   intrusion_set_name         167 non-null    object
 2   processed_sequence_tokens  167 non-null    object
dtypes: object(3)
memory usage: 4.0+ KB

## Calculate non-unique technique counts

### Subtask:
Calculate the total count of each technique across all sequences, including repeated occurrences within a single sequence, and their corresponding specificity scores.

**Reasoning**:
Flatten the list of lists of technique tokens, calculate the frequency of each token, and calculate the specificity based on the frequency.

In [ ]:
from collections import Counter

# Flatten the list of lists in the 'processed_sequence_tokens' column
all_techniques = [token for sequence in processed_sequences_df['processed_sequence_tokens'] for token in sequence]

# Calculate the frequency of each technique (Non-Unique_total_count)
technique_counts = Counter(all_techniques)

# Create a pandas Series from the frequency counts
technique_counts_series = pd.Series(technique_counts, name='Non-Unique_total_count')

# Calculate the Non-Unique_specificity_count_per_technique (1 / count)
non_unique_specificity = 1 / technique_counts_series

# Create a DataFrame for non-unique counts and specificity
non_unique_analysis_df = pd.DataFrame({
    'technique_name': technique_counts_series.index,
    'non_unique_total_count': technique_counts_series.values,
    'non-unique_specificity_count_per_technique': non_unique_specificity.values
})

# Display the first few rows of the non-unique analysis DataFrame
print("non-unique technique analysis:")
display(non_unique_analysis_df.head())

non-unique technique analysis:

,technique_name,non_unique_total_count,non-unique_specificity_count_per_technique
0,T1588,103,0.009709
1,T1566,139,0.007194
2,T1053,59,0.016949
3,T1059,256,0.003906
4,T1204,132,0.007576

## Calculate unique technique counts

### Subtask:
For each sequence, determine the unique techniques present and calculate the total count of each unique technique across all sequences, along with their corresponding specificity scores.

**Reasoning**:
Determine the unique techniques per sequence, flatten them, count occurrences, and calculate specificity.

In [ ]:
# Create a list of unique techniques for each sequence
unique_techniques_per_sequence = [list(set(sequence)) for sequence in processed_sequences_df['processed_sequence_tokens']]

# Flatten the list of lists of unique techniques
all_unique_techniques = [token for unique_sequence in unique_techniques_per_sequence for token in unique_sequence]

# Calculate the frequency of each unique technique (Unique_total_count)
unique_technique_counts = Counter(all_unique_techniques)

# Create a pandas Series from the unique technique counts
unique_technique_counts_series = pd.Series(unique_technique_counts, name='Unique_total_count')

# Calculate the Unique_specificity_count_per_technique (1 / count)
unique_specificity = 1 / unique_technique_counts_series

# Display the first few entries of the unique technique counts and specificity
print("Sample unique technique counts:")
display(unique_technique_counts_series.head())

print("\nSample unique specificity scores:")
display(unique_specificity.head())

Sample unique technique counts:

T1036    82
T1204    96
T1566    94
T1588    78
T1027    85
Name: Unique_total_count, dtype: int64

Sample unique specificity scores:

T1036    0.012195
T1204    0.010417
T1566    0.010638
T1588    0.012821
T1027    0.011765
Name: Unique_total_count, dtype: float64

**Reasoning**:
Combine the unique technique counts and specificity scores into a DataFrame.

In [ ]:
# Create a DataFrame for unique counts and specificity
unique_analysis_df = pd.DataFrame({
    'technique_name': unique_technique_counts_series.index,
    'unique_total_count': unique_technique_counts_series.values,
    'unique_specificity_count_per_technique': unique_specificity.values
})

# Display the first few rows of the unique analysis DataFrame
print("\n unique technique analysis:")
display(unique_analysis_df.head())

 unique technique analysis:

  technique_name  unique_total_count  unique_specificity_count_per_technique
0          T1036                  82                                0.012195
1          T1204                  96                                0.010417
2          T1566                  94                                0.010638
3          T1588                  78                                0.012821
4          T1027                  85                                0.011765

## Create analytical dataframe

### Subtask:
Create a new DataFrame that combines the non-unique and unique technique count and specificity analysis results.

**Reasoning**:
Merge the non-unique and unique technique analysis DataFrames on the 'تکنیک' column and display the head of the resulting DataFrame.

In [ ]:
# Merge the non-unique and unique analysis DataFrames
analytical_df = pd.merge(non_unique_analysis_df, unique_analysis_df, on='technique_name', how='outer')

# Display the first few rows of the combined DataFrame
print("Combined technique analysis DataFrame:")
display(analytical_df.head())

Combined technique analysis DataFrame:

,technique_name,non_unique_total_count,non-unique_specificity_count_per_technique,unique_total_count,unique_specificity_count_per_technique
0,T1001,5,0.200000,5,0.200000
1,T1003,97,0.010309,55,0.018182
2,T1005,43,0.023256,43,0.023256
3,T1006,2,0.500000,2,0.500000
4,T1007,14,0.071429,14,0.071429

## Save analytical data

### Subtask:
Save the combined analytical DataFrame to a CSV file.

**Reasoning**:
Save the combined analytical DataFrame to a CSV file.

In [ ]:
# Define the output path for the CSV file
output_csv_path = '/content/technique_analysis.csv'

# Save the DataFrame to the specified CSV file
analytical_df.to_csv(output_csv_path, index=False, encoding='utf-8')

print(f"Combined technique analysis saved to CSV file: {output_csv_path}")

Combined technique analysis saved to CSV file: /content/technique_analysis.csv

## Summary:

### Data Analysis Key Findings

*   The analysis successfully calculated both the total (non-unique) count and the unique count for each technique across all processed sequences.
*   The specificity score (1/count) was calculated for both non-unique and unique counts for each technique.
*   The results were combined into a single DataFrame containing columns for 'تکنیک', 'Non-Unique\_total\_count', 'Non-Unique\_specificity\_count\_per\_technique', 'Unique\_total\_count', and 'Unique\_specificity\_count\_per\_technique'.
*   The final analytical data was saved to a CSV file named `technique_analysis.csv`.

### Insights or Next Steps

*   The calculated specificity scores can be used to identify techniques that appear less frequently and might be more indicative of specific attack patterns.
*   Further analysis could involve comparing the non-unique and unique counts to understand the frequency of technique repetition within sequences.

In [ ]:
# Define the output path for the Excel file
output_excel_path = '/content/extended_technique_analysis.xlsx'

# Save the analytical DataFrame to an Excel file
try:
    analytical_df.to_excel(output_excel_path, index=False)
    print(f"Analytical data saved to Excel file: {output_excel_path}")
except ImportError:
    print("Saving to Excel requires the 'openpyxl' library.")
    print("Please install it by running: !pip install openpyxl")
    # Fallback to CSV if openpyxl is not installed
    output_csv_path = '/content/extended_technique_analysis.csv'
    analytical_df.to_csv(output_csv_path, index=False, encoding='utf-8')
    print(f"Analytical data saved to CSV file instead: {output_csv_path}")

Analytical data saved to Excel file: /content/extended_technique_analysis.xlsx

In [ ]:
import pandas as pd
import ast

# مرحله 1: خواندن فایل‌ها
processed_df = pd.read_excel('processed_sequences_table.xlsx')
technique_analysis_df = pd.read_csv('technique_analysis.csv')

# مرحله 2: ساخت دیکشنری mapping از technique_id به unique_specificity_count_per_technique
# فقط ردیف‌هایی که technique_name معتبر دارند
valid_techniques = technique_analysis_df.dropna(subset=['technique_name'])
spec_dict = dict(zip(valid_techniques['technique_name'], valid_techniques['unique_specificity_count_per_technique']))

# مرحله 3: تابع برای پردازش هر ردیف
def compute_total_specificity(token_list_str):
    try:
        tokens = ast.literal_eval(token_list_str)
    except:
        tokens = []
    # حذف تکرارها و نگهداری ترتیب
    seen = set()
    unique_tokens = []
    for t in tokens:
        if t not in seen:
            unique_tokens.append(t)
            seen.add(t)
    # محاسبه مجموع specificity
    total = 0.0
    for t in unique_tokens:
        total += spec_dict.get(t, 0.0)  # اگر تکنیک وجود نداشت، 0 اضافه شود
    return unique_tokens, total

# مرحله 4: اعمال تابع روی هر ردیف
processed_df[['processed_sequence_unique_tokens', 'total_specificity']] = processed_df['processed_sequence_tokens'].apply(
    lambda x: pd.Series(compute_total_specificity(x))
)

# مرحله 5: انتخاب ستون‌های مورد نیاز
result_df = processed_df[[
    'intrusion_set_id',
    'intrusion_set_name',
    'processed_sequence_unique_tokens',
    'total_specificity'
]]

# نمایش نتیجه
print(result_df.head())

# ذخیره به عنوان فایل CSV (اختیاری)
result_df.to_csv('apt_total_specificity.csv', index=False)

                                    intrusion_set_id intrusion_set_name  \
0  intrusion-set--c4d50cdf-87ce-407d-86d8-8628834...           APT-C-36
1  intrusion-set--6a2e693f-24e5-451a-9f88-b36a108...               APT1
2  intrusion-set--c47f937f-1022-4f42-8525-e7a4779...              APT12
3  intrusion-set--d6e88e18-81e8-4709-82d8-973095d...              APT16
4  intrusion-set--090242d7-73fc-4738-af68-20162f7...              APT17

                    processed_sequence_unique_tokens  total_specificity
0  [T1588, T1566, T1053, T1059, T1204, T1027, T10...           0.167477
1  [T1583, T1584, T1585, T1588, T1566, T1059, T10...           0.645529
2                [T1566, T1203, T1204, T1102, T1568]           0.167267
3                                            [T1584]           0.041667
4                                     [T1583, T1585]           0.062998

In [ ]:
# Save the result_df to an Excel file
output_excel_path = 'apt_total_specificity.xlsx'
try:
    result_df.to_excel(output_excel_path, index=False)
    print(f"DataFrame successfully saved to {output_excel_path}")
except ImportError:
    print("Saving to Excel requires the 'openpyxl' library.")
    print("Please install it by running: !pip install openpyxl")
except Exception as e:
    print(f"An error occurred while saving the Excel file: {e}")

DataFrame successfully saved to apt_total_specificity.xlsx